#!/bin/bash
#
# Written 2013 by Darko Krizic, darko@krizic.net

# TODO: Error handling
# TODO: Arguement handling

BonjourName="$1" 
BonjourType="$2"
name=$(echo $BonjourName | sed -e 's/ /\\\\032/g')
result=$(/usr/bin/avahi-browse -p -t -k "$BonjourType" 2>/dev/null | grep $name)
count=$(echo $result | awk -F\; '{print $4}' | sed -e 's/\\032/ /g' | grep "$BonjourName" | wc -l)
if [ $count -eq 0 ]
then
	echo "Service $BonjourName of type $BonjourType not found"
	exit 2
fi
output=$(echo $result | sed -e 's/\\032/ /g' | awk -F\; '{print $4"."$6" ("$5")"'})
echo "$output"
exit 0
